services:
  dev:
    image: mikespub/seblucas-cops:dev
    build:
      context: . 
      dockerfile: docker/Dockerfile.alpine
      target: dev-envs
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    #environment:
    #  - PORT=80
    ports:
      - '8080:80'
    volumes:
      - ./config_local.php:/app/config_local.php
      - ./lib:/app/lib
      - ./test:/app/test
