services:
  dev:
    image: mikespub/seblucas-cops:dev
    build:
      context: . 
      dockerfile: docker/Dockerfile.alpine
      target: dev-envs
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    #environment:
    #  - PORT=80
    ports:
      - '8080:80'
    volumes:
      - ./config/local.php:/app/config/local.php
      - ./src:/app/src
      - ./tests:/app/tests
